project:
  type: website
  output-dir: docs
  

website:
  title: "Digital Soil Mapping"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started-r.qmd
        text: Getting Started R
        menu:
        - href: download-install-r.qmd
          text: Download and Installation R
        - href: introduction-to-r
          text: Introduction to R
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



